portfolioproject/myportfolio/urls.py
from django.urls import path  # Importa la función path del módulo urls de Django, que se usa para definir rutas de URL.
from . import views  # Importa el módulo views desde el mismo directorio, donde se definen las funciones que manejan las vistas.

urlpatterns = [
    path('', views.home, name='home'),  # Define una ruta de URL. La cadena vacía ('') indica la raíz del sitio web. Esta ruta llama a la función home en views y le asigna el nombre 'home'.
    path('contacto/nuevo/', views.contacto_nuevo, name='contacto_nuevo'),
    path('contacto/<int:pk>/', views.contacto_detalle, name='contacto_detalle'),
    path('contacto/<int:pk>/editar/', views.contacto_editar, name='contacto_editar'),
    path('contacto/<int:pk>/eliminar/', views.contacto_eliminar, name='contacto_eliminar'),
    path('contactos/', views.contacto_lista, name='contacto_lista'),
    path('contacto/confirmacion/', views.contacto_confirmacion, name='contacto_confirmacion'),
]

portfolioproject/portfolioproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myportfolio.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolioproject/myportfolio/models.py
from django.db import models  # Importa el módulo models de Django, que proporciona un marco para trabajar con modelos.

# Crear tus modelos aquí.

class Categoria(models.Model):  # Define la clase Categoria que hereda de models.Model.
    nombre = models.CharField(max_length=100, unique=True)  # Campo de texto con longitud máxima de 100 caracteres, debe ser único.

    def __str__(self):  # Método que define la representación en cadena del objeto.
        return self.nombre  # Devuelve el nombre de la categoría.

class Tecnologia(models.Model):  # Define la clase Tecnologia que hereda de models.Model.
    nombre = models.CharField(max_length=50, unique=True)  # Campo de texto con longitud máxima de 50 caracteres, debe ser único.

    def __str__(self):  # Método que define la representación en cadena del objeto.
        return self.nombre  # Devuelve el nombre de la tecnología.

# Modelo para los proyectos de portafolio.

class Proyecto(models.Model):  # Define la clase Proyecto que hereda de models.Model.
    titulo = models.CharField(max_length=200)  # Campo de texto con longitud máxima de 200 caracteres.
    imagen = models.ImageField(upload_to='proyectos/')  # Campo de imagen, las imágenes se suben a la carpeta 'proyectos/'.
    descripcion = models.TextField()  # Campo de texto largo para la descripción.
    tecnologias = models.ManyToManyField(Tecnologia)  # Relación muchos a muchos con el modelo Tecnologia.
    link_sitio = models.URLField(max_length=200)  # Campo de URL con longitud máxima de 200 caracteres para el link del sitio.
    link_repositorio = models.URLField(max_length=200)  # Campo de URL con longitud máxima de 200 caracteres para el link del repositorio.
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)  # Relación muchos a uno con el modelo Categoria, borrado en cascada.

    def __str__(self):  # Método que define la representación en cadena del objeto.
        return self.titulo  # Devuelve el título del proyecto.

# Defino el modelo del formulario de contacto.

class Contacto(models.Model):  # Define la clase Contacto que hereda de models.Model.
    nombre = models.CharField(max_length=100)  # Campo de texto con longitud máxima de 100 caracteres.
    email = models.EmailField()  # Campo de email.
    mensaje = models.TextField()  # Campo de texto largo para el mensaje.
    fecha = models.DateTimeField(auto_now_add=True)  # Campo de fecha y hora, se establece automáticamente a la fecha y hora actuales.

    def __str__(self):  # Método que define la representación en cadena del objeto.
        return self.nombre  # Devuelve el nombre del contacto.

portfolioproject/myportfolio/forms.py
from django import forms  # Importa el módulo forms de Django, que proporciona un marco para trabajar con formularios.
from .models import Contacto  # Importa el modelo Contacto desde el archivo models.py del mismo directorio.

class ContactoForm(forms.ModelForm):  # Define una clase Contacto que hereda de forms.ModelForm.
    class Meta:  # Clase interna Meta para definir metadatos sobre el formulario.
        model = Contacto  # Especifica que el formulario está basado en el modelo Contacto.
        fields = ['nombre', 'email', 'mensaje']  # Define los campos del modelo que se incluirán en el formulario.
        widgets = {  # Define los widgets para personalizar los campos del formulario.
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),  # Personaliza el campo 'nombre' con un widget TextInput y añade la clase 'form-control' para estilos CSS.
            'email': forms.EmailInput(attrs={'class': 'form-control'}),  # Personaliza el campo 'email' con un widget EmailInput y añade la clase 'form-control' para estilos CSS.
            'mensaje': forms.TextInput(attrs={'class': 'form-control'}),  # Personaliza el campo 'mensaje' con un widget TextInput y añade la clase 'form-control' para estilos CSS.
        }

portfolioproject/myportfolio/views.py
#agrego get_object_or_404 , redirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
#agrego contacto
from .models import Proyecto, Contacto
from .forms import ContactoForm

# Create your views here que el inicio que muestra los proyectos 
def home(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'index.html', {'proyectos':proyectos})

#4 agrego por acá
def contacto_nuevo(request):
    if request.method == "POST":
        form = ContactoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('contacto_confirmacion')
    else:
        form = ContactoForm()
    return render(request, 'myportfolio/contacto_formulario.html', {'form': form})

@login_required
def contacto_detalle(request,pk):
    contacto = get_object_or_404(Contacto, pk=pk)
    return render(request, 'myportfolio/contacto_detalle.html', {'contacto': contacto})

@login_required
def contacto_editar(request, pk):
    contacto = get_object_or_404(Contacto, pk=pk)  # Obtén el objeto Contacto con la clave primaria (pk) especificada, o devuelve un 404 si no existe.
    if request.method == "POST":
        form = ContactoForm(request.POST, instance=contacto)  # Crea una instancia del formulario con los datos POST y el contacto existente.
        if form.is_valid():
            form.save()  # Guarda los cambios en el objeto Contacto.
            return redirect('contacto_detalle', pk=contacto.pk)  # Redirige a la vista contacto_detalle después de guardar.
    else:
        form = ContactoForm(instance=contacto)  # Crea una instancia del formulario con el contacto existente.
    return render(request, 'myportfolio/contacto_formulario.html', {'form': form})  # Renderiza la plantilla contacto_formulario.html con el formulario.

@login_required
def contacto_eliminar(request, pk):
    contacto = get_object_or_404(Contacto, pk=pk)
    contacto.delete()
    return redirect('contacto_lista')

login_required
def contacto_lista(request):
    contactos = Contacto.objects.all()
    return render (request, 'myportfolio/contacto_lista.html', {'contactos': contactos})

def contacto_confirmacion(request):
    return render(request, 'myportfolio/contacto_confirmacion.html')

portfolioproject/myportfolio/templates/base_generic.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Portafolio{% endblock %}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    {% bootstrap_javascript %}
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

portfolioproject/myportfolio/templates/index.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Portfolio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#hero">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#skills">Skills</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section id="hero" class="text-center text-white d-flex justify-content-center align-items-center">
        <div class="container">
            <h1 class="display-4">Welcome to My Portfolio</h1>
            <p class="lead">Showcasing My Skills and Projects</p>
        </div>
    </section>

    <!-- Skills Section -->
    <section id="skills" class="py-5">
        <div class="container">
            <h2 class="text-center">My Skills</h2>
            <div class="row">
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">HTML</h5>
                            <p class="card-text">Proficient in HTML5 for building semantic web pages.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">CSS</h5>
                            <p class="card-text">Experienced with CSS3 for styling and layout design.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">JavaScript</h5>
                            <p class="card-text">Skilled in JavaScript for interactive web applications.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


 <!-- Portfolio Section -->

<section id="projects" class="py-5">

    <div class="container">
        <h2 class="text-center">Mis Proyectos</h2>
        <div class="row">
            {% for proyecto in proyectos %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ proyecto.imagen.url}}" alt="{{proyecto.titulo}}"   class="card-img-top">
                    <div class="car-body">
                        <h5 class="card-title">{{proyecto.titulo}}</h5>
                        <p class="card-text">{{proyecto.descripcion}}</p>
                        <a href="{{proyecto.link_sitio}}" class="btn btn-primary" target="_blank">Ver sitio</a>
                        <a href="{{proyecto.link_repositorio}}" class="btn btn-primary" target="_blank">Ver repositorio</a>
                    </div>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>

</section>

     <!-- Contact Section -->
     <section id="contact" class="py-5 bg-light">
        <div class="container">
            <h2 class="text-center">Contáctame</h2>
            <form method="POST" action="{% url 'contacto_nuevo' %}" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="id_nombre" name="nombre" required>
                    <div class="invalid-feedback">Por favor ingresa un nombre.</div>
                </div>
                <div class="mb-3">
                    <label for="id_email" class="form-label">Correo</label>
                    <input type="email" class="form-control" id="id_email" name="email" required>
                    <div class="invalid-feedback">Por favor ingresa un correo.</div>
                </div>
                <div class="mb-3">
                    <label for="id_mensaje" class="form-label">Mensaje</label>
                    <textarea class="form-control" id="id_mensaje" name="mensaje" rows="3" required></textarea>
                    <div class="invalid-feedback">Por favor ingresa un mensaje.</div>
                </div>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </section>

    {% bootstrap_javascript %}
    <script src="{% static 'js/script.js'%}"></script>
</body>
</html>

portfolioproject/myportfolio/templates/myportfolio/contacto_confirmacion.html
{% extends 'base_generic.html' %}

{%  block content %}

<div class="container mt-5">
    <h2>Gracias por tu mensaje</h2>
    <p>Nos pondremos en contacto pronto</p>
   
</div>
{% endblock %}

portfolioproject/myportfolio/templates/myportfolio/contacto_detalle.html
{% extends 'base_generic.html' %}

{%  block content %}

<div class="container mt-5">
    <h2>Detalle del Contacto</h2>
    <p><strong>Nombre:</strong>{{contacto.nombre}}</p>
    <p><strong>Email:</strong>{{contacto.email}}</p>
    <p><strong>Mensaje:</strong>{{contacto.mensaje}}</p>
    <a href="{%  url 'contacto_editar' contacto.pk %}" class="btn btn-primary">Editar</a>
    <form method="POST" action="{% url 'contacto_eliminar' contacto.pk %}" style="display:inline;"> 
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>

    </form>
    <a href="{% url 'contacto_lista' %}" class="btn btn-secondary">Volver a la lista</a>
</div>
{% endblock %}

portfolioproject/myportfolio/templates/myportfolio/contacto_editar.html
{% extends 'base_generic.html' %}

{%  block content %}

<div class="container mt-5">
    <h2>Editar Contacto</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        {{form.as_p}}
       <button type="submit" class=" btn btn-primary">Guardar</button>
      <a href="{%  url 'contacto_lista' %}" class="btn btn-secondary">Cancelar</a> 
   </form>
   
</div>
{% endblock %}

portfolioproject/myportfolio/templates/myportfolio/contacto_formulario.html
{% extends 'base_generic.html' %}

{% block content %}

<div class="container mt-5">
    <h2>Editar Contacto</h2>
    <form method="POST" class="needs-validation" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar</button>
        <a href="{% url 'contacto_lista' %}" class="btn btn-secondary">Cancelar</a> <!-- Corrige btn-seconday a btn-secondary -->
    </form>
</div>

{% endblock %}

portfolioproject/myportfolio/templates/myportfolio/contacto_lista.html
{% extends 'base_generic.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="text-center mb-4">Contactos Recibidos</h2>
    <div class="table-responsive">
      <table class="table table-hover align-middle">
        <thead class="table-dark">
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Email</th>
            <th scope="col">Mensaje</th>
            <th scope="col" class="text-center">Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for contacto in contactos %}
            <tr>
              <td>{{ contacto.nombre }}</td>
              <td>{{ contacto.email }}</td>
              <td>{{ contacto.mensaje }}</td>
              <td class="text-center">
                <a href="{% url 'contacto_detalle' contacto.pk %}" class="btn btn-info btn-sm m-1">Ver</a>
                <a href="{% url 'contacto_editar' contacto.pk %}" class="btn btn-warning btn-sm m-1">Editar</a>
                <form method="POST" action="{% url 'contacto_eliminar' contacto.pk %}" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger btn-sm m-1">Eliminar</button>
                </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}